### ISSUE TITLE
Convert to Typescript

### ISSUE THREAD

**Issue by volt-roy** [acmpesuecc/VantaGreen#4]
Convert everything to Typescript for type-safety

**Comment by ankitkumar099** [comment]
can u asssign for this issue ??

**Comment by 411sst** [comment]
can i get assigned?

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by volt-roy** [comment]
> can i get assigned to this

assigned

**Comment by sid-nc** [comment]
can i get more details on this
Do i need to convert all the files to typescript

**Comment by samarth777** [comment]
can you assign this to me

**Comment by volt-roy** [comment]
assigned @samarth777

**Comment by sujay1844** [comment]
can you assign this to me since @samarth777 hasn't shown progress in 2 hours
